[INPUT]
Z = "FORWARD"
S = "BACKWARD"
D = "RIGHT"
Q = "LEFT"
Alt = "ROLL_RIGHT"
Shift = "ROLL_LEFT"
U = "JUMP"
I = "POWERSLIDE"
M = "BOOST"
B = "TARGET_CAM"
Tab = "CYCLE_TARGETS"
Space = "SWITCH_CAR"

[CAMERA]
FOV = 110
DISTANCE = 270
HEIGHT = 110
ANGLE = 3